FROM nginx:alpine
# UPDATE because of vulnerabilities warnings 
RUN apk update && apk upgrade --no-cache

COPY . .

## <-- Uncomment if you created the nginx.conf
#COPY nginx.conf /etc/nginx/conf.d/default.conf  

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]